### ISSUE TITLE
wait... hdf input files are being modified?

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/imars_dags#54]
Seeing a weird problem from `l1a_2_geo` all the sudden:

```
 [2018-05-15 16:53:57,728] {bash_operator.py:80} INFO - Temporary script location: /tmp/airflowtmp3g6lmx8j//tmp/airflowtmp3g6lmx8j/l1a_2_geo6b7n6a5r
 [2018-05-15 16:53:57,728] {bash_operator.py:88} INFO - Running command: 
             export OCSSWROOT=/opt/ocssw      && 
             source /opt/ocssw/OCSSW_bash.env && 
             OUT_PATH=/srv/imars-objects/airflow_tmp/gom_myd01_to_myd0_otis_l2_20180111T202000_geofile         && 
             /opt/ocssw/run/scripts/modis_GEO.py \
                 --output=$OUT_PATH \
                 /srv/imars-objects/modis_aqua_gom/myd01/A2018011.2020.hdf && 
             [[ -s $OUT_PATH ]]
         
- Output:
 - Traceback (most recent call last):
 File "/opt/ocssw/run/scripts/modis_GEO.py", line 187, in <module>
 - sys.exit(main())
 - File "/opt/ocssw/run/scripts/modis_GEO.py", line 173, in main
  - modis_env(m)
 - File "/opt/ocssw/run/scripts/modules/modis_utils.py", line 263, in modis_env
 - self.start, self.stop, self.sat_name = modis_timestamp(self.file)
 - File "/opt/ocssw/run/scripts/modules/modis_utils.py", line 151, in modis_timestamp
 - sat_name = meta['ASSOCIATEDPLATFORMSHORTNAME'].lower()
 - KeyError: 'ASSOCIATEDPLATFORMSHORTNAME'
 - Command exited with return code 1
```

but... nothing has changed? After picking through the code and a lot of head scratching I noticed that the l1 hdf files had an unusually recent mtime. I pulled a backup file and came across this:

```
tylar@tylardesk:~/Downloads$ diff A2018011.2020.hdf A2018011.2020_backup.hdf 
Binary files A2018011.2020.hdf and A2018011.2020_backup.hdf differ

tylar@tylardesk:~/Downloads$ file A2018011.2020_backup.hdf 
A2018011.2020_backup.hdf: Hierarchical Data Format (version 4) data
tylar@tylardesk:~/Downloads$ file A2018011.2020.hdf 
A2018011.2020.hdf: Hierarchical Data Format (version 5) data
```

So some script thought it was fit to modify the **input** and covert it to hdf5? :roll_eyes:

**Comment by 7yl4r** [comment]
closest to relevant info I could find:

>There is also a possibility that the "owt16_modis_stats_101111.hdf" file is corrupt.  Compare the output of "md5sum /usr/local/seadas/ocssw/run/data/modis/class/owt16_modis_stats_101111.hdf" with "md5sum /home/pypro/seadas-7.4/ocssw/run/data/modis/class/owt16_modis_stats_101111.hdf" on your other system.  If they are the same, the file is unlikely to be corrupt.  If they are different, they could still be OK, as **some software opens hdf4 libraries with "write" enabled to update some sort of access log** without changing the data.  On the other (working) system, you have group write permission, but the failing system only allows the owner to write to the file. 

[ref](https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?pid=36170;hl=hdf%20permission)

Well, I think it's a terrible idea, but apparently it is accepted so let's focus on how to work with it.

1. remove airflow's write permission (but I believe I saw before ocssw will just error out)
2. make imars-etl *actually* extract to local tmp
3. accept that "archived files" are subject to random change and might become corrupted at any time.
4. ...?

Gosh I wish I could think of a 4th option, (2) and (3) both suck. I guess we'll live with (3) for now until I can make time to come around and implement (2).

**Comment by 7yl4r** [comment]
@dotis : I am worried about letting airflow loose if it is going to modify the myd01 files as noted above. We could end up with a lot of corrupted and potentially not backed up L1s. 

Have you had this issue before?

**Comment by 7yl4r** [comment]
I believe this is fixed now that `imars-etl` has a proper `extract` fn. I have changed permissions on the myd01 files so that airflow cannot write them. 

These are the files that may have been corrupted or overwritten:

```
MariaDB [imars_product_metadata]> SELECT id,filepath,date_time,status_id FROM file WHERE product_id=5 AND status_id IN (1,3,4);
+------+-----------------------------------------------------------+---------------------+-----------+
| id   | filepath                                                  | date_time           | status_id |
+------+-----------------------------------------------------------+---------------------+-----------+
| 6557 | /srv/imars-objects/modis_aqua_gom/myd01/A2018012.0825.hdf | 2018-01-12 08:25:00 |         1 |
| 6731 | /srv/imars-objects/modis_aqua_gom/myd01/A2018011.2020.hdf | 2018-01-11 20:20:00 |         1 |
| 6733 | /srv/imars-objects/modis_aqua_gom/myd01/A2018012.0645.hdf | 2018-01-12 06:45:00 |         4 |
| 6734 | /srv/imars-objects/modis_aqua_gom/myd01/A2018012.0650.hdf | 2018-01-12 06:50:00 |         1 |
+------+-----------------------------------------------------------+---------------------+-----------+
```

**Comment by 7yl4r** [comment]
The two files below need to be replaced, the other two are fine.

```
+------+-----------------------------------------------------------+---------------------+-----------+
| id   | filepath                                                  | date_time           | status_id |
+------+-----------------------------------------------------------+---------------------+-----------+
| 6557 | /srv/imars-objects/modis_aqua_gom/myd01/A2018012.0825.hdf | 2018-01-12 08:25:00 |         1 |
| 6733 | /srv/imars-objects/modis_aqua_gom/myd01/A2018012.0645.hdf | 2018-01-12 06:45:00 |         4 |
+------+-----------------------------------------------------------+---------------------+-----------+
```

I downloaded them manually from [oceancolor's direct data access](https://oceandata.sci.gsfc.nasa.gov/MODIS-Aqua/L1/2018/012/):

```
-rw-rw-r--. 1 airflow airflow  47M May 23 21:53 A2018012064500.L1A_LAC.bz2
-rw-rw-r--. 1 airflow airflow  43M May 23 21:52 A2018012082500.L1A_LAC.bz2
```

unzipped and replaced the corrupted files:

```
[root@thing2 airflow_tmp]# bzip2 -d A2018012064500.L1A_LAC.bz2 
[root@thing2 airflow_tmp]# bzip2 -d A2018012082500.L1A_LAC.bz2 
[root@thing2 myd01]# mv A2018012064500.L1A_LAC A2018012.0645.hdf
mv: overwrite `A2018012.0645.hdf'? y
[root@thing2 myd01]# mv A2018012082500.L1A_LAC A2018012.0825.hdf
mv: overwrite `A2018012.0825.hdf'? y
```

all should be good now.
