### ISSUE TITLE
upg to seadas 7.5

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/imars_dags#56]
I ran into some issues when trying to use ocssw 7.5.

[Here is a forum discussion on compiling it](https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?pid=37410), although really we just need binaries that work since we're not compiling a custom version like Brock.

**Comment by 7yl4r** [comment]
first issue is with `modis_GEO.py`:

```
-bash-4.2$ export OCSSWROOT=/opt/ocssw
-bash-4.2$ source /opt/ocssw/OCSSW_bash.env
-bash-4.2$ OUT_PATH=/srv/imars-objects/airflow_tmp/proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
Directory /opt/ocssw/var does not exist.
Using current working directory for storing the ancillary database file: ancillary_data.db
/opt/ocssw/run/bin/linux_64/geogen_modis: error while loading shared libraries: libdf.so.0: cannot open shared object file: No such file or directory
*** ERROR: geogen_modis failed to produce a geolocation file.
*** Validation test failed for geolocation file: proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile
ERROR: MODIS geolocation processing failed.
```

**Comment by 7yl4r** [comment]
`/opt/ocssw/var` indeed DNE. Previously this was `/opt/ocssw/run/var`.

and yes, it did stick the `ancillary_db` in my cwd:

```
-rw-r--r--.  1 airflow airflow 4.0K May 21 16:36 ancillary_data.db
```

`mkdir /opt/ocssw/var`  and try again:

```
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
Traceback (most recent call last):
  File "/opt/ocssw/run/scripts/modis_GEO.py", line 187, in <module>
    sys.exit(main())
  File "/opt/ocssw/run/scripts/modis_GEO.py", line 178, in main
    m.atteph()
  File "/opt/ocssw/run/scripts/modules/modis_GEO_utils.py", line 217, in atteph
    get.findweb()
  File "/opt/ocssw/run/scripts/modules/anc_utils.py", line 479, in findweb
    ancdatabase.openDB()
  File "/opt/ocssw/run/scripts/modules/ancDB.py", line 20, in openDB
    conn = sqlite3.connect(self.dbfile, timeout=30)
sqlite3.OperationalError: unable to open database file
```

No files were put into `/opt/ocssw/var/` or cwd. `cp -R /opt/ocssw/run/var/* /opt/ocssw/var/.` & try again:

```
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
/opt/ocssw/run/bin/linux_64/geogen_modis: error while loading shared libraries: libdf.so.0: cannot open shared object file: No such file or directory
*** ERROR: geogen_modis failed to produce a geolocation file.
*** Validation test failed for geolocation file: proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile
ERROR: MODIS geolocation processing failed.
```

progress...

**Comment by 7yl4r** [comment]
Installing `hdf4`, `libX11-devel`, and `zlib-devel` via `yum` had no effect on the issue.

**Comment by 7yl4r** [comment]
Hmm, there is what we need:

```
[root@imars-airflow-test ~]# find / -iname libdf.so.0
/opt/ocssw/run/opt/linux_64/lib/libdf.so.0
```

**Comment by 7yl4r** [comment]
So looking at the environment file (after making sure it was updated). The following change might make sense given the change from `bin3` to `opt` in 7.5:

```
[root@imars-airflow-test ocssw]# diff OCSSW_bash.env OCSSW_bash.env_backup_2018-05-21 
60c60
< export LIB3_BIN=${OCSSWROOT}/run/opt/$OCSSW_ARCH
---
> export LIB3_BIN=${OCSSWROOT}/run/bin3/$OCSSW_ARCH
```

Now we get:

```
-bash-4.2$ export OCSSWROOT=/opt/ocssw
-bash-4.2$ source /opt/ocssw/OCSSW_bash.env
-bash-4.2$ OUT_PATH=/srv/imars-objects/airflow_tmp/proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
/opt/ocssw/run/opt/linux_64/hdp is not executable.
Error!  dump_metadata failed.
```

which is because:

```
[root@imars-airflow-test ocssw]# ls -lh /opt/ocssw/run/opt/linux_64/
total 16K
drwxr-xr-x. 2 root root 4.0K May 14 13:29 bin
drwxr-xr-x. 7 root root   86 May 14 13:29 include
drwxr-xr-x. 4 root root 8.0K May 21 16:14 lib
drwxr-xr-x. 9 root root  158 May 14 13:29 share
```

`hdp` is actually at 
```
[root@imars-airflow-test ocssw]# find /opt/ocssw/run/opt/linux_64/ -name hdp
/opt/ocssw/run/opt/linux_64/bin/hdp
```

so let's try:
```
[root@imars-airflow-test ocssw]# diff OCSSW_bash.env OCSSW_bash.env_backup_2018-05-21 
60c60
< export LIB3_BIN=${OCSSWROOT}/run/opt/$OCSSW_ARCH/bin
---
> export LIB3_BIN=${OCSSWROOT}/run/bin3/$OCSSW_ARCH
```

nope. we're back to:
```
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
/opt/ocssw/run/bin/linux_64/geogen_modis: error while loading shared libraries: libdf.so.0: cannot open shared object file: No such file or directory
*** ERROR: geogen_modis failed to produce a geolocation file.
*** Validation test failed for geolocation file: proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile
ERROR: MODIS geolocation processing failed.
```

**Comment by 7yl4r** [comment]
So let's put the env file back and try something dumb to deal with the hdp issue:

```
[root@imars-airflow-test ocssw]# ln -s /opt/ocssw/run/opt/linux_64/bin/hdp /opt/ocssw/run/opt/linux_64/hdp
```

aaand we're back around to

```
-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
/opt/ocssw/run/opt/linux_64/hdp: error while loading shared libraries: libmfhdf.so.0: cannot open shared object file: No such file or directory
Error!  dump_metadata failed.
```

**Comment by 7yl4r** [comment]
The addition of `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ocssw/run/opt/linux_64/lib/` to `OCSSW_bash.env` has had no effect on the issue.

But hold on a second... what is going on here?
```
[root@imars-airflow-test ocssw]# ls -lh /opt/ocssw/run/opt/linux_64/lib/libdf.
libdf.a         libdf.la        libdf.so.0.0.0  
```
did that find command lie to me or has something changed?

**Comment by 7yl4r** [comment]
so...

```
[root@imars-airflow-test ocssw]# ln -s /opt/ocssw/run/opt/linux_64/lib/libdf.so.0.0.0  /opt/ocssw/run/opt/linux_64/lib/libdf.so.0

-bash-4.2$ /opt/ocssw/run/scripts/modis_GEO.py --output=$OUT_PATH  /srv/imars-objects/airflow_tmp/A2018011.2020.hdf
Directory /opt/ocssw/var does not exist.
Using current working directory for storing the ancillary database file: ancillary_data.db
/opt/ocssw/run/bin/linux_64/geogen_modis: error while loading shared libraries: libmfhdf.so.0: cannot open shared object file: No such file or directory
*** ERROR: geogen_modis failed to produce a geolocation file.
*** Validation test failed for geolocation file: proc_myd01_to_myd0_otis_l2_gom_20180111T202000_geofile6
ERROR: MODIS geolocation processing failed.
```

`libmfhdf.so.0` now, ey? :roll_eyes:

**Comment by 7yl4r** [comment]
Looks like the instructions at [build_ocssw/rhel](https://seadas.gsfc.nasa.gov/build_ocssw/rhel/) are about as good as it gets. Not too bad for centos7, but centos6 is a bit of pain.

Also looks like I may need to rethink how to get ocssw onto the airflow nodes.

**Comment by 7yl4r** [comment]
Trying out centos7 install on userproc:

```
$ sudo yum install https://centos7.iuscommunity.org/ius-release.rpm
$ sudo yum erase git
$ sudo yum install epel-release 
$ sudo yum install git2u
$ curl https://oceandata.sci.gsfc.nasa.gov/ocssw/install_ocssw.py > install_ocssw.py
$ chmod +x ./install_ocssw.py
$ ./install_ocssw.py  -v -i /opt/ocssw -c --aqua --terra
```

seems to have worked. :+1:

**Comment by 7yl4r** [comment]
ocssw installation via puppet using install_ocssw.py is working on airflow nodes. We still can't get this on seashell easily because of the older OS version, but I think things are working well enough to close this.
