### ISSUE TITLE
airflow nodes randomly(?) dropped from celery?

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/imars_dags#67]
Looking at the [celery flower gui](http://imars-airflow01.marine.usf.edu:5555/) I notice that nodes 11 and 15 have disconnected, but  metrics from [the airflow grafana view](http://grafana.marine.usf.edu:3000/dashboard/db/airflow?refresh=5m&orgId=1&from=now-7d&to=now) show these nodes still taking jobs. The counts on the celery flower are not changing for those nodes though. Opening up the celery flower UI from my laptop and the "disconnected" nodes don't even show up:

![image](https://user-images.githubusercontent.com/1051390/40589799-07da1fd2-61c2-11e8-915b-d72799a87ecf.png)

Logging into the nodes and poking around a bit didn't reveal anything notable.

**Comment by 7yl4r** [comment]
Logged into `imars-airflow15` and did `systemctl restart airflow-worker`. Worker is now showing up in celery again.

**Comment by 7yl4r** [comment]
11, 13, 15 have gone "offline" since I brought things back up this morning.

I feel this may be related to the recurring problem I am having at USF-IMARS/imars_dags/issues/35

**Comment by 7yl4r** [comment]
Restarting the flower clears these "Offline" workers, and they don't come back until the worker restarts.

These lines from the worker log may be relevant:
```
May 29 21:14:48 imars-airflow13.marine.usf.edu airflow[1298]: File "/usr/lib64/python3.4/site-packages/MySQLdb/connections.py", line 204, in __init__
May 29 21:14:48 imars-airflow13.marine.usf.edu airflow[1298]: super(Connection, self).__init__(*args, **kwargs2)
May 29 21:14:48 imars-airflow13.marine.usf.edu airflow[1298]: sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1040, 'Too many connections')
May 29 21:14:48 imars-airflow13.marine.usf.edu airflow[1298]: [2018-05-29 21:14:48,290] {jobs.py:2533} ERROR - Exception while trying to heartbeat! Sleeping for 5.0 seconds
```

**Comment by 7yl4r** [comment]
Yep, that "too many connections" error is definitely the problem here, and I am fairly certain [that poke_until_cleanup hack](https://github.com/USF-IMARS/imars_dags/blob/master/util/etl_tools/cleanup.py#L48) is to blame.

**Comment by 7yl4r** [comment]
Huh... here's another one that might cause it:

```
May 29 23:11:55 imars-airflow15.marine.usf.edu airflow[29475]: [2018-05-29 23:11:55,131] {celery_executor.py:54} ERROR - Command 'airflow run proc_myd01_to_myd0_otis_l2_gom poke_until_tmp_cleanup_done 2005-06-27T18:15:00 --local -sd /home/airflow/dags/imars_dags/dags/processing/myd01_to_myd0_otis_l2/myd01_to_myd0_otis_l2.py' returned non-zero exit status 1
May 29 23:11:55 imars-airflow15.marine.usf.edu airflow[29475]: [2018-05-29 23:11:55,192: ERROR/ForkPoolWorker-12] Task airflow.executors.celery_executor.execute_command[08b8a9d7-5db4-4372-986c-a53929de4005] raised unexpected: AirflowException('Celery command failed',)
May 29 23:11:55 imars-airflow15.marine.usf.edu airflow[29475]: Traceback (most recent call last):
May 29 23:11:55 imars-airflow15.marine.usf.edu airflow[29475]: File "/usr/lib/python3.4/site-packages/airflow/executors/celery_executor.py", line 52, in execute_command
```

**Comment by 7yl4r** [comment]
Jeez... one more:
```
May 30 15:18:04 imars-airflow12.marine.usf.edu airflow[4799]: billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
May 30 15:18:04 imars-airflow12.marine.usf.edu airflow[4799]: [2018-05-30 15:18:04,771: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)
May 30 15:18:04 imars-airflow12.marine.usf.edu airflow[4799]: Traceback (most recent call last):
May 30 15:18:04 imars-airflow12.marine.usf.edu airflow[4799]: File "/usr/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
```
apparently this can happen a lot of ways.

**Comment by 7yl4r** [comment]
This seems to be consistently happening to 15 & 12 (with the `Celery command failed'` error), but not the other three.

**Comment by 7yl4r** [comment]
another variation of "celery command failed":

```
May 31 11:36:51 imars-airflow11.marine.usf.edu airflow[1265]: sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') [SQL: 'UPDATE task_instance SET start_date=%s, state=%s, try_number=%s, hostname=%s, job_id=%s, operator=%s, pid=%s WHERE task_instance.task_id = %s AND task_instance.dag_id = %s AND task_instance.execution_date = %s'] [parameters: (datetime.datetime(2018, 5, 31, 11, 36, 51, 572093), 'running', 1, 'imars-airflow11.marine.usf.edu', 96265, 'SqlSensor', 846, 'check_for_to_loads', 'file_trigger_catchall_unused', datetime.datetime(2018, 5, 31, 11, 34, 48, 25936))]
May 31 11:36:52 imars-airflow11.marine.usf.edu airflow[1265]: [2018-05-31 11:36:52,039] {celery_executor.py:54} ERROR - Command 'airflow run file_trigger_catchall_unused check_for_to_loads 2018-05-31T11:34:48.025936 --local -sd /home/airflow/dags/imars_dags/dags/file_triggers/catchall_unused.py' returned non-zero exit status 1
May 31 11:36:52 imars-airflow11.marine.usf.edu airflow[1265]: [2018-05-31 11:36:52,138: ERROR/ForkPoolWorker-3] Task airflow.executors.celery_executor.execute_command[4377cc25-9cd1-4c07-b882-d9dc441e61c3] raised unexpected: AirflowException('Celery command failed',)
```

**Comment by 7yl4r** [comment]
From what I can tell this is a common issue with celery workers. Newer versions seem to try to handle these better, but a lot seems to boil down to restarting the workers. I wonder if a `sysctl restart airflow-worker` cronjob would help? It is possible that would create other issues though due higher numbers of killed jobs.

**Comment by 7yl4r** [comment]
Better idea: The service *is* getting started back after a failure, but somehow it does not start back the right way.

It should be possible to modify the service definition to do things "right" (whatever that is) using [`ExecReload`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload=) or one of the other fancy options available.

**Comment by 7yl4r** [comment]
On the airflow slack channel it was suggested that the broker (RabbitMQ) may be at fault here.

I have checked over airflow.cfg again, browsed logs, inspected `--debug` outputs and have no leads; let's turn it off and then on again.

```
[root@imars-airflow01 ~]# rabbitmqctl stop_app
[root@imars-airflow01 ~]# rabbitmqctl start_app
```

(Possibly) useful [management web UI](https://www.rabbitmq.com/management.html) for rabbitMQ running at http://imars-airflow01.marine.usf.edu:15672.
Login w/ `airflow_rabbitmq_user` & pw from puppet.
I need to open the port with puppet.
Things look okay in there I think.

One unexplained finding: the queues listed in the web UI are correct, but the CLI is different (and only has the default):

```
[root@imars-airflow01 ~]# rabbitmqctl list_queues name messages_ready messages_unacknowledged
Listing queues ...
default	7	0
...done.
```

**Comment by 7yl4r** [comment]
[Celery#4758](https://github.com/celery/celery/issues/4758) looks very relevant.

I have made [this gist](https://gist.github.com/7yl4r/d3c5b68d305fea53c4fa926d89ae2903) trying to spell out how to trace worker troubles.
Still too many moving mysterious parts for me to pin down this issue.

**Comment by 7yl4r** [comment]
Workaround may be to [increase the heartbeat setting in celery](https://github.com/celery/celery/issues/4817#issuecomment-398634402)
